# Generated by Django 3.1.3 on 2020-11-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aktualnosci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Naglowek', models.CharField(max_length=50)),
                ('Tresc', models.CharField(max_length=100)),
                ('Istotnosc', models.IntegerField()),
            ],
        ),
    ]
