# Generated by Django 3.1.3 on 2020-11-23 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_aktualnosci'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tytul', models.CharField(max_length=50)),
                ('Tresc', models.CharField(max_length=200)),
                ('Odpowiedz', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tytul', models.CharField(max_length=30)),
                ('Zdjecie', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Uslugi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NazwaUslugi', models.CharField(max_length=30)),
                ('TypUslugi', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypUzytkownika', models.CharField(max_length=20)),
                ('Imie', models.CharField(max_length=50)),
                ('Nazwisko', models.CharField(max_length=80)),
                ('Haslo', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=100)),
                ('NrTelefonu', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Rezerwacja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataRozpoczecia', models.DateTimeField()),
                ('DataZakonczenia', models.DateTimeField()),
                ('Uwagi', models.CharField(max_length=50)),
                ('IdUslugi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.uslugi')),
                ('IdUzytkownika', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.uzytkownik')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramLojalnosciowy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nagroda', models.CharField(max_length=30)),
                ('Punkty', models.IntegerField()),
                ('IdUzytkownika', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.uzytkownik')),
            ],
        ),
        migrations.CreateModel(
            name='Buty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rozmiar', models.IntegerField()),
                ('Id_Rezerwacji', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.rezerwacja')),
            ],
        ),
    ]
