# Generated by Django 3.1.3 on 2020-11-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_buty_faq_galeria_programlojalnosciowy_rezerwacja_uslugi_uzytkownik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='test_photos')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
