# Generated by Django 3.1.3 on 2020-11-29 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_test_photos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='Test_Photos',
        ),
    ]
