# Generated by Django 3.1.3 on 2020-11-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20201129_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktualnosci',
            name='Tresc',
            field=models.TextField(max_length=200),
        ),
    ]
