# Generated by Django 3.1.3 on 2020-11-28 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_uzytkownicy_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uzytkownicy',
            name='username',
        ),
    ]
