# Generated by Django 3.1.3 on 2020-11-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_remove_uzytkownicy_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzytkownicy',
            name='username',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
    ]
