# Generated by Django 3.1.3 on 2020-11-28 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_auto_20201128_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uzytkownicy',
            name='nrtelefonu',
        ),
    ]
