# Generated by Django 3.1.3 on 2020-11-28 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_remove_uzytkownicy_nrtelefonu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='uzytkownicy',
        ),
    ]
